name: .NET Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: windows-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: .NET restore
      run: dotnet restore --nologo --configfile Nuget.config

    - name: .NET clean
      run: dotnet clean --nologo

    - name: .NET build
      run: dotnet build --nologo --no-restore --configuration Debug

    - name: .NET test
      run: dotnet test --nologo --no-restore --no-build --blame-hang-timeout 1min
  